#!/usr/bin/bash
 
if ! tmux -S /var/tmp/session attach -t server ; then
    echo "Error connecting to server session. Try sudo ~/bin/start"
    echo "If that doesn't work, run sudo rm /var/tmp/session and try again"
    exit 1
fi
